// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package v0

import (
	"context"

	"github.com/Khan/genqlient/graphql"
	"github.com/google/uuid"
)

// __duplicateProjectInput is used internally by genqlient
type __duplicateProjectInput struct {
	Id         uuid.UUID `json:"id"`
	GroupID    uuid.UUID `json:"groupID"`
	SubGroupID uuid.UUID `json:"subGroupID"`
	Name       string    `json:"name"`
}

// GetId returns __duplicateProjectInput.Id, and is useful for accessing the field via an interface.
func (v *__duplicateProjectInput) GetId() uuid.UUID { return v.Id }

// GetGroupID returns __duplicateProjectInput.GroupID, and is useful for accessing the field via an interface.
func (v *__duplicateProjectInput) GetGroupID() uuid.UUID { return v.GroupID }

// GetSubGroupID returns __duplicateProjectInput.SubGroupID, and is useful for accessing the field via an interface.
func (v *__duplicateProjectInput) GetSubGroupID() uuid.UUID { return v.SubGroupID }

// GetName returns __duplicateProjectInput.Name, and is useful for accessing the field via an interface.
func (v *__duplicateProjectInput) GetName() string { return v.Name }

// __getGroupInput is used internally by genqlient
type __getGroupInput struct {
	Path string `json:"path"`
}

// GetPath returns __getGroupInput.Path, and is useful for accessing the field via an interface.
func (v *__getGroupInput) GetPath() string { return v.Path }

// __getRepoInput is used internally by genqlient
type __getRepoInput struct {
	Id uuid.UUID `json:"id"`
}

// GetId returns __getRepoInput.Id, and is useful for accessing the field via an interface.
func (v *__getRepoInput) GetId() uuid.UUID { return v.Id }

// duplicateProjectDuplicateProjectRepo includes the requested fields of the GraphQL type Repo.
type duplicateProjectDuplicateProjectRepo struct {
	// - v0.RepoID
	Id uuid.UUID `json:"id"`
}

// GetId returns duplicateProjectDuplicateProjectRepo.Id, and is useful for accessing the field via an interface.
func (v *duplicateProjectDuplicateProjectRepo) GetId() uuid.UUID { return v.Id }

// duplicateProjectResponse is returned by duplicateProject on success.
type duplicateProjectResponse struct {
	// Create a copy of a repo, optionally specifying the target project and project environment
	DuplicateProject duplicateProjectDuplicateProjectRepo `json:"duplicateProject"`
}

// GetDuplicateProject returns duplicateProjectResponse.DuplicateProject, and is useful for accessing the field via an interface.
func (v *duplicateProjectResponse) GetDuplicateProject() duplicateProjectDuplicateProjectRepo {
	return v.DuplicateProject
}

// getGroupProject includes the requested fields of the GraphQL type Project.
type getGroupProject struct {
	// - v0.ProjectID or v1.GroupID
	Id           uuid.UUID                                       `json:"id"`
	Name         string                                          `json:"name"`
	Environments []getGroupProjectEnvironmentsProjectEnvironment `json:"environments"`
}

// GetId returns getGroupProject.Id, and is useful for accessing the field via an interface.
func (v *getGroupProject) GetId() uuid.UUID { return v.Id }

// GetName returns getGroupProject.Name, and is useful for accessing the field via an interface.
func (v *getGroupProject) GetName() string { return v.Name }

// GetEnvironments returns getGroupProject.Environments, and is useful for accessing the field via an interface.
func (v *getGroupProject) GetEnvironments() []getGroupProjectEnvironmentsProjectEnvironment {
	return v.Environments
}

// getGroupProjectEnvironmentsProjectEnvironment includes the requested fields of the GraphQL type ProjectEnvironment.
type getGroupProjectEnvironmentsProjectEnvironment struct {
	// - v0.EnvironmentID or v1.SubGroupID
	Id   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// GetId returns getGroupProjectEnvironmentsProjectEnvironment.Id, and is useful for accessing the field via an interface.
func (v *getGroupProjectEnvironmentsProjectEnvironment) GetId() uuid.UUID { return v.Id }

// GetName returns getGroupProjectEnvironmentsProjectEnvironment.Name, and is useful for accessing the field via an interface.
func (v *getGroupProjectEnvironmentsProjectEnvironment) GetName() string { return v.Name }

// getGroupResponse is returned by getGroup on success.
type getGroupResponse struct {
	// - v0.ProjectID or v1.GroupID
	Project getGroupProject `json:"project"`
}

// GetProject returns getGroupResponse.Project, and is useful for accessing the field via an interface.
func (v *getGroupResponse) GetProject() getGroupProject { return v.Project }

// getRepoRepo includes the requested fields of the GraphQL type Repo.
type getRepoRepo struct {
	// - v0.RepoID
	Id uuid.UUID `json:"id"`
}

// GetId returns getRepoRepo.Id, and is useful for accessing the field via an interface.
func (v *getRepoRepo) GetId() uuid.UUID { return v.Id }

// getRepoResponse is returned by getRepo on success.
type getRepoResponse struct {
	Repo getRepoRepo `json:"repo"`
}

// GetRepo returns getRepoResponse.Repo, and is useful for accessing the field via an interface.
func (v *getRepoResponse) GetRepo() getRepoRepo { return v.Repo }

// The query or mutation executed by duplicateProject.
const duplicateProject_Operation = `
mutation duplicateProject ($id: UUID!, $groupID: UUID, $subGroupID: UUID, $name: String!) {
	duplicateProject(input: {enabled:true,environmentID:$subGroupID,id:$id,projectID:$groupID,name:$name}) {
		id
	}
}
`

func duplicateProject(
	ctx context.Context,
	client graphql.Client,
	id uuid.UUID,
	groupID uuid.UUID,
	subGroupID uuid.UUID,
	name string,
) (*duplicateProjectResponse, error) {
	req := &graphql.Request{
		OpName: "duplicateProject",
		Query:  duplicateProject_Operation,
		Variables: &__duplicateProjectInput{
			Id:         id,
			GroupID:    groupID,
			SubGroupID: subGroupID,
			Name:       name,
		},
	}
	var err error

	var data duplicateProjectResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getGroup.
const getGroup_Operation = `
query getGroup ($path: String) {
	project(path: $path) {
		id
		name
		environments {
			id
			name
		}
	}
}
`

func getGroup(
	ctx context.Context,
	client graphql.Client,
	path string,
) (*getGroupResponse, error) {
	req := &graphql.Request{
		OpName: "getGroup",
		Query:  getGroup_Operation,
		Variables: &__getGroupInput{
			Path: path,
		},
	}
	var err error

	var data getGroupResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by getRepo.
const getRepo_Operation = `
query getRepo ($id: UUID) {
	repo(id: $id) {
		id
	}
}
`

func getRepo(
	ctx context.Context,
	client graphql.Client,
	id uuid.UUID,
) (*getRepoResponse, error) {
	req := &graphql.Request{
		OpName: "getRepo",
		Query:  getRepo_Operation,
		Variables: &__getRepoInput{
			Id: id,
		},
	}
	var err error

	var data getRepoResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
